builds:
  - binary: check-debian-reboot-required
    goos:
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: Arthur1
    name: check-debian-reboot-required
